import React from "react";
import {
  Card,
  Button,
  Space,
  Alert,
  Typography,
  Divider,
  Tag,
  Empty
} from "antd";
import {
  CheckCircleOutlined,
  CopyOutlined,
  RedoOutlined
} from "@ant-design/icons";
import { useDraftStore } from "../../../store/draft-store";

const { Paragraph, Text } = Typography;

interface ReviewStepProps {
  onReset: () => void;
}

export function ReviewStep({ onReset }: ReviewStepProps) {
  const { generatedDraft, capturedJob, reset } = useDraftStore();

  function handleReset() {
    reset();
    onReset();
  }

  if (!generatedDraft || !capturedJob) {
    return (
      <Card style={{ minHeight: 300 }}>
        <Empty description="No draft generated" />
      </Card>
    );
  }

  const { output, metadata } = generatedDraft;

  return (
    <Card title="Step 3: Review & Copy" style={{ minHeight: 300 }} bordered={false}>
      <Space direction="vertical" style={{ width: "100%" }}>
        <Alert
          type="success"
          icon={<CheckCircleOutlined />}
          message="Draft Generated"
          description={`Generated by ${metadata.provider} (${metadata.model})`}
          showIcon
        />

        <Divider style={{ margin: "12px 0" }} />

        <div>
          <Tag color="blue" style={{ marginBottom: "8px" }}>
            Subject Line
          </Tag>
          <Paragraph strong style={{ marginBottom: "4px" }}>
            {output.subjectLine}
          </Paragraph>
        </div>

        <div>
          <Tag color="cyan" style={{ marginBottom: "8px" }}>
            Key Highlights
          </Tag>
          <ul style={{ marginBottom: "16px", paddingLeft: "20px" }}>
            {output.keyHighlights.map((highlight, i) => (
              <li key={i} style={{ fontSize: "13px", marginBottom: "4px" }}>
                {highlight}
              </li>
            ))}
          </ul>
        </div>

        <div>
          <Tag color="green" style={{ marginBottom: "8px" }}>
            Draft Letter
          </Tag>
          <div
            style={{
              backgroundColor: "#f6f8fb",
              border: "1px solid #dbe2ea",
              borderRadius: "8px",
              padding: "12px",
              maxHeight: "150px",
              overflowY: "auto",
              fontSize: "12px",
              lineHeight: "1.5",
              whiteSpace: "pre-wrap",
              wordBreak: "break-word"
            }}
          >
            {output.coverLetter}
          </div>
        </div>

        <Divider style={{ margin: "12px 0" }} />

        <Space direction="vertical" style={{ width: "100%", fontSize: "12px" }}>
          <Text type="secondary">
            💡 Tip: Copy the draft and personalize it with your own details before applying.
          </Text>
        </Space>

        <Space style={{ width: "100%" }}>
          <Button onClick={handleReset} icon={<RedoOutlined />} style={{ flex: 1 }}>
            New Job
          </Button>
          <Button
            type="primary"
            icon={<CopyOutlined />}
            onClick={() => {
              navigator.clipboard.writeText(output.coverLetter);
            }}
            style={{ flex: 1 }}
          >
            Copy Letter
          </Button>
        </Space>
      </Space>
    </Card>
  );
}
